### PR TITLE
Added support for global Config object in runtime

### PR DESCRIPTION
**Pull request by nedpranson**
# Added support for [Config ](https://github.com/customrealms/bukkit-runtime/pull/9) object
To create config use
```ts
import { saveConfig } from '@customrealms/core'

const config= saveConfig() // Creates config.yml
const dataConfig= saveConfig('data') // Creates data.yml

// Put data
config.getConfig().set('message', 'this is a message')

// Get data
console.log(defualtConfig.getConfig().getString('message'))

// saves config
config.saveConfig()

// Reload config
config.reloadConfig()

```
# Note
There are some function missing, but will be added

### CODE REVIEW

**Comment by DoggersFor1** [comment]
This is great. Thanks!

**Comment by AL1L** [comment]
Haven't gotten a chance to look at it in-depth, but rather than overriding the hello world example, could you make a new one?

**Comment by connerdouglass** [comment]
I support adding the ability to read/write config yml files. I'm going to test this out and see how I like it – initially thinking we might want to do some minor cleanup of the Config API we create. I'll get back to you shortly!

**Review by nedpranson — COMMENTED** [review]
FileConfiguration needs more functions, but it should work good.

**Comment by ghost** [comment]
I really really would like this to be a feature, Sadly @AL1L hasn't reviewed the code yet.

**Comment by ghost** [comment]
thank you.

**Pull request merged**
